matrix:
  include:
    - language: java 
      before_script:
        - cd chessEngine 
      script:
        - mvn install

    - language: java
      before_script:
        - cd chessEngine
        - mvn install
        - cp target/*.jar ../api/src/main/resources/chess-engine.jar
        - cd ../api
      script:
        - mvn install 
