matrix:
  include:
    - language: java 
      before_script:
        - cd chessEngine 
      script:
        - mvn install
      after_script:
        - cp target/*.jar ../api/src/main/resources/chess-engine.jar 

    - language: java
      before_script:
        - cd api 
      script:
        - mvn install 

    - language: javascript
      before_script:
        - cd chess-engine-frontend 
        - npm install
      script:
        - npm run test
